spring:
  application:
    name: spring-cloud-api-gateway
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:8081/edone_train
    username: postgres
    password: Password1!
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
 client:
   serviceURL:
     defaultZone: http://localhost:8900/eureka